apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: hello-world
resources:
  - namespace.yaml
  - serviceaccount.yaml
  - deployment.yaml
  - service.yaml
  - ingress.yaml
  - network-policy.yaml
  - scan-config.yaml
  - trivy-cronjob.yaml
