apiVersion: v1
kind: ConfigMap
metadata:
  name: scan-config
  namespace: hello-world
data:
  image: ghcr.io/sesamesesamum/example_k8s:3f6acae62df8b8b9ee99f1e41da596da4a53203a
  ntfy-url: https://ntfy.sh/hello-world-scan-example-k8s
